model:
  class_path: tite.module.TiteModule
  init_args:
    model:
      class_path: tite.model.BertForPreTraining
      init_args:
        config:
          class_path: tite.model.BertConfig
          init_args:
            vocab_size: 30522
            num_hidden_layers: 12
            hidden_size: 768
            num_attention_heads: 12
            intermediate_size: 3072
            positional_embedding_type: rotary
            rotary_interleaved: true
            hidden_act: gelu_pytorch_tanh
            norm_location: post
            norm_type: layer
        masked_language_modeling: true
        enhanced_masked_auto_encoding: true
        enhanced_causal_auto_encoding: false
        bow_auto_encoding: true
    tokenizer:
      class_path: tite.model.TiteTokenizer
      init_args:
        vocab_file: tokenizers/bert-base-uncased/vocab.txt
        tokenizer_file: tokenizers/bert-base-uncased/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512
    validate_on_glue: true
    validate_on_trec_dl: true
    log_gradients: false
