model:
  class_path: tite.module.TiteModule
  init_args:
    student:
      class_path: tite.model.TiteModel
      init_args:
        config:
          class_path: tite.model.TiteConfig
          init_args:
            vocab_size: 30522
            num_hidden_layers: 12
            hidden_sizes: [768, 768, 768, 768, 768, 768, 768, 768, 768, 768, 768, 768]
            num_attention_heads: [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]
            intermediate_sizes: [3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072, 3072]
            kernel_sizes: [null, 2, 2, 2, null, 2, 2, 2, null, 2, 2, 2]
            strides: [null, 2, 2, 2, null, 2, 2, 2, null, 2, 2, 2]
            positional_embedding_type: rotary
            upscale_hidden_sizes: true
            pooling_strategy: mean_conv
    tokenizer:
      class_path: tite.tokenizer.TiteTokenizer
      init_args:
        vocab_file: tokenizers/tite/vocab.txt
        tokenizer_file: tokenizers/tite/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512
    teachers:
    - class_path: tite.teacher.MAETeacher
      init_args:
        padid: 0
        enhanced: true
    - class_path: tite.teacher.BOWTeacher
      init_args:
        vocab_size: 30522
        padid: 0
    predictors:
    - class_path: tite.predictor.MAEEnhancedDecoder
      init_args:
        hidden_size: 768
        num_attention_heads: 12
        intermediate_size: 3072
        # hidden_size: 1536
        # num_attention_heads: 24
        # intermediate_size: 6144
        # hidden_size: 3072
        # num_attention_heads: 48
        # intermediate_size: 12288
        query_strategy: embx
        mask_id: 103
        mask_prob: 0.5
    - class_path: tite.predictor.BOWDecoder
      init_args:
        vocab_size: 30522
        hidden_size: 768
    losses:
    - class_path: tite.loss.MAECrossEntropy
      init_args:
        vocab_size: 30522
    - class_path: tite.loss.BOWBinaryCrossEntropy
      init_args:
        vocab_size: 30522
    log_additional_metrics: false
    validate_on_glue: true
    validate_on_msmarco: true
    log_gradients: true
