model:
  class_path: tite.module.TiteModule
  init_args:
    student:
      class_path: tite.bert.BertModel
      init_args:
        config:
          class_path: tite.bert.BertConfig
          init_args:
            num_hidden_layers: 12
            pooling: true
            unpadding: true
    tokenizer:
      class_path: tite.tokenizer.TiteTokenizer
      init_args:
        vocab_file: tokenizers/bert-base-uncased/vocab.txt
        tokenizer_file: tokenizers/bert-base-uncased/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512
    teachers:
      - class_path: tite.teacher.OrderTeacher
      - class_path: tite.teacher.CopyStudent
    predictors:
      - class_path: tite.predictor.BlockOrderPredictor
      - class_path: tite.predictor.BlockEmbeddingPredictor
    losses:
      - class_path: tite.loss.ApproxOrderMSE
      - class_path: torch.nn.MSELoss
    log_additional_metrics: false
    validate_on_glue: true
    validate_on_msmarco: false