model:
  class_path: tite.module.TiteModule
  init_args:
    student:
      class_path: tite.bert.BertModel
      init_args:
        config:
          class_path: tite.bert.BertConfig
          init_args:
            num_hidden_layers: 12
            pooling: true
            unpadding: true
    tokenizer:
      class_path: tite.tokenizer.TiteTokenizer
      init_args:
        vocab_file: tokenizers/bert-base-uncased/vocab.txt
        tokenizer_file: tokenizers/bert-base-uncased/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512
    teacher:
      class_path: tite.teacher.Identity
    predictor:
      class_path: tite.predictor.BlockEmbeddingPredictor
    loss:
      class_path: torch.nn.MSELoss
    validate_on_glue: true
    validate_on_msmarco: true