data:
  class_path: tite.datasets.IRDatasetsDataModule
  init_args:
    batch_size: 128
    inference_batch_size: 256
    tokenizer:
      class_path: tite.tokenizer.TiteTokenizer
      init_args:
        vocab_file: tokenizers/bert-base-uncased/vocab.txt
        tokenizer_file: tokenizers/bert-base-uncased/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512
    trainset: [msmarco-passage/train/triples-small, triples]
    valset: [msmarco-passage/trec-dl-2019/judged, scoreddocs]