data:
  class_path: tite.datasets.FineWebDataModule
  # init_args:
  #   path: HuggingFaceFW/fineweb-edu
  #   name: default
  #   batch_size: 128
  #   num_workers: 4
  #   streaming: true
  init_args:
    path: arrow
    data_files:
      train: /mnt/ceph/storage/data-tmp/current/fschlatt/.cache/huggingface/datasets/HuggingFaceFW___fineweb-edu/default/0.0.0/5b89d1ea9319fe101b3cbdacd89a903aca1d6052/fineweb-edu-train-*.arrow
    batch_size: 128
    num_workers: 4
    streaming: true
  # init_args:
  #   path: parquet
  #   data_files:
  #     train: /mnt/ceph/storage/corpora/corpora-thirdparty/corpus-fineweb-edu/snapshots/5b89d1ea9319fe101b3cbdacd89a903aca1d6052/data/CC-MAIN-*/train-*.parquet
  #   batch_size: 128
  #   num_workers: 4
  #   streaming: true
