data:
  class_path: tite.datasets.IRDatasetsDataModule
  init_args:
    batch_size: 256
    inference_batch_size: 256
    trainset: [msmarco-passage/train/triples-small, triples]
    valset: [msmarco-passage/trec-dl-2019/judged, scoreddocs]