data:
  class_path: tite.datasets.FineWebDataModule
  # init_args:
  #   path: HuggingFaceFW/fineweb-edu
  #   name: default
  #   batch_size: 128
  #   num_workers: 8
  #   streaming: true
  init_args:
    path: arrow
    data_files:
      train: /mnt/ceph/storage/data-tmp/current/fschlatt/.cache/huggingface/datasets/HuggingFaceFW___fineweb-edu/default/0.0.0/5b89d1ea9319fe101b3cbdacd89a903aca1d6052/fineweb-edu-train-*.arrow
    batch_size: 128
    num_workers: 8
    streaming: true
    max_length: 256
    tokenizer:
      class_path: tite.tokenizer.TiteTokenizer
      init_args:
        vocab_file: tokenizers/bert-base-uncased/vocab.txt
        tokenizer_file: tokenizers/bert-base-uncased/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512
  # init_args:
  #   path: parquet
  #   data_files:
  #     train: /mnt/ceph/storage/corpora/corpora-thirdparty/corpus-fineweb-edu/snapshots/5b89d1ea9319fe101b3cbdacd89a903aca1d6052/data/CC-MAIN-*/train-*.parquet
  #   batch_size: 128
  #   num_workers: 8
  #   streaming: true
