data:
  class_path: tite.datasets.FineWebDataModule
  init_args:
    # path: HuggingFaceFW/fineweb-edu
    path: arrow
    data_files:
      train: /mnt/ceph/storage/corpora/corpora-thirdparty/corpus-fineweb-edu/default/0.0.0/5b89d1ea9319fe101b3cbdacd89a903aca1d6052/fineweb-edu-train-*.arrow
    # path: parquet
    # data_files:
    #   train: /mnt/ceph/storage/corpora/corpora-thirdparty/corpus-fineweb-edu/snapshots/5b89d1ea9319fe101b3cbdacd89a903aca1d6052/data/CC-MAIN-*/train-*.parquet
    batch_size: 128
    num_workers: 8
    streaming: true
    collator:
      class_path: tite.datasets.TransformationCollator
      init_args:
        text_keys:
        - text
        - null
        max_length: 256
        student_string_transformations: null
        teacher_string_transformations: null
        student_token_transformations: null
        student_token_transformations:
        - class_path: tite.transformations.MLMMaskTokens
          init_args:
            vocab_size: 30522
            mask_id: 103
            cls_id: 101
            sep_id: 102
            mask_prob: 0.3
        teacher_token_transformations: null