model:
  class_path: tite.msmarco_module.MSMARCOModule
  init_args:
    similarity: dot
    model:
      class_path: tite.bert.HFBertModel
      init_args:
        model_name_or_path: bert-base-uncased
        pooling: first
    tokenizer:
      class_path: tite.tokenizer.TiteTokenizer
      init_args:
        vocab_file: tokenizers/bert-base-uncased/vocab.txt
        tokenizer_file: tokenizers/bert-base-uncased/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512