model:
  class_path: tite.module.TiteModule
  init_args:
    student:
      class_path: tite.bert.HFBertModel
      init_args:
        model_name_or_path: bert-base-uncased
    tokenizer:
      class_path: tite.tokenizer.TiteTokenizer
      init_args:
        vocab_file: tokenizers/bert-base-uncased/vocab.txt
        tokenizer_file: tokenizers/bert-base-uncased/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512
    teachers:
    - class_path: tite.teacher.MLMTeacher
      init_args:
        padid: 0
    predictors:
    - class_path: tite.predictor.HFMLMDecoder
      init_args:
        model_name_or_path: bert-base-uncased
    losses:
    - class_path: tite.loss.MAECrossEntropy
      init_args:
        vocab_size: 30522
    validate_on_glue: true
    validate_on_msmarco: true