optimizer:
  class_path: tite.lars.LARS
  init_args:
    lr_weights: 0.2
    lr_biases: 0.005
    weight_decay_filter: true
    lars_adaptation_filter: true
lr_scheduler:
  class_path: LARSScheduler
  init_args:
    num_warmup_steps: 3000
    base_factor: 4
