model:
  class_path: tite.module.TiteModule
  init_args:
    student:
      class_path: tite.model.TiteModel
      init_args:
        config:
          class_path: tite.model.TiteConfig
          init_args:
            vocab_size: 30522
            num_hidden_layers: 12
            hidden_size:
              - 768
              - 768
              - 768
              - 768
              - 768
              - 768
              - 768
              - 768
              - 768
              - 768
              - 768
              - 768
            num_attention_heads:
              - 12
              - 12
              - 12
              - 12
              - 12
              - 12
              - 12
              - 12
              - 12
              - 12
              - 12
              - 12
            intermediate_size:
              - 3072
              - 3072
              - 3072
              - 3072
              - 3072
              - 3072
              - 3072
              - 3072
              - 3072
              - 3072
              - 3072
              - 3072
            kernel_size:
              - null
              - 3
              - null
              - 3
              - null
              - 3
              - null
              - 3
              - null
              - 3
              - null
              - 3
            stride:
              - null
              - 3
              - null
              - 3
              - null
              - 3
              - null
              - 3
              - null
              - 3
              - null
              - 3
    tokenizer:
      class_path: tite.tokenizer.TiteTokenizer
      init_args:
        vocab_file: tokenizers/bert-base-uncased/vocab.txt
        tokenizer_file: tokenizers/bert-base-uncased/tokenizer.json
        do_lower_case: True
        unk_token: '[UNK]'
        sep_token: '[SEP]'
        pad_token: '[PAD]'
        cls_token: '[CLS]'
        mask_token: '[MASK]'
      dict_kwargs:
        model_max_length: 512
    transformations:
      - class_path: tite.transformations.MaskTokens
        init_args:
          maskid: 103
          clsid: 101
          sepid: 102
          mask_prob: 0.3
    predictor:
      tite.predictor.Identity
    loss:
      class_path: tite.loss.BarlowTwins
      init_args:
        lmbda: 0.5
        num_features: 768
    max_length: 128