# lightning.pytorch==2.2.0.post0
seed_everything: 42
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  logger:
    class_path: CustomWandbLogger
    init_args:
      project: tite
    dict_kwargs:
      entity: tite
  callbacks: null
  max_steps: 1000000
  accumulate_grad_batches: 1
  gradient_clip_val: 10
  detect_anomaly: false