trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  precision: bf16-mixed
  num_nodes: 1
  callbacks:
  - class_path: tite.callbacks.DummyImportCallback
  logger: false
  enable_checkpointing: false