seed_everything: 0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  callbacks:
  - class_path: ModelCheckpoint
  - class_path: tite.utils.callbacks.DummyImportCallback
  max_epochs: null
  max_steps: 10100
  val_check_interval: 20000
  check_val_every_n_epoch: null
  accumulate_grad_batches: 8
  gradient_clip_val: 1
